[package]
name = "lazy_auth"
version = "0.1.0"
edition = "2021"
[[bin]]
path = "./src/examples/pair.rs"
name = "pair"
[[bin]]
path = "./src/examples/validate.rs"
name = "validate"
[dependencies]
base64 = { version = "0.13.0" }
reqwest = { version = "0.11.11", features = [ "blocking" ] }
